using System;
using System.Globalization;
using System.Reflection;
using System.Text;

namespace FriendlyEnvars;

/// <summary>
/// The exception thrown when FriendlyEnvars cannot bind an environment variable to a property.
/// </summary>
/// <remarks>
/// <para>
/// Environment variables routinely carry secrets. Every exception the library raises is therefore built
/// only from metadata that is already present in your source code — the environment-variable name, the
/// options type and name, the property, the target type, the configured culture, the binder type and the
/// full type name of the underlying cause. The offending value, the underlying exception's message and
/// the underlying exception object itself are never retained or reproduced, so a leaked log or crash
/// report cannot disclose a secret.
/// </para>
/// <para>
/// Because the cause is not retained, <see cref="Exception.InnerException"/> is always <see langword="null"/>
/// on an exception the library generated; use <see cref="CauseType"/> to identify what went wrong.
/// </para>
/// </remarks>
public sealed class EnvarsException : Exception
{
    /// <summary>
    /// Initializes a new instance of the <see cref="EnvarsException"/> class.
    /// </summary>
    /// <remarks>
    /// Instances created through this constructor carry no structured metadata: every diagnostic property
    /// on this type, including <see cref="FailureKind"/>, is <see langword="null"/>.
    /// </remarks>
    public EnvarsException()
    {
    }

    /// <summary>
    /// Initializes a new instance of the <see cref="EnvarsException"/> class with a specified message.
    /// </summary>
    /// <param name="message">The message that describes the error.</param>
    /// <remarks>
    /// Instances created through this constructor carry no structured metadata: every diagnostic property
    /// on this type, including <see cref="FailureKind"/>, is <see langword="null"/>.
    /// </remarks>
    public EnvarsException(string message) : base(message)
    {
    }

    /// <summary>
    /// Initializes a new instance of the <see cref="EnvarsException"/> class with a specified message and
    /// the exception that caused it.
    /// </summary>
    /// <param name="message">The message that describes the error.</param>
    /// <param name="innerException">The exception that is the cause of this exception.</param>
    /// <remarks>
    /// Instances created through this constructor carry no structured metadata: every diagnostic property
    /// on this type, including <see cref="FailureKind"/>, is <see langword="null"/>.
    /// </remarks>
    public EnvarsException(string message, Exception innerException) : base(message, innerException)
    {
    }

    /// <summary>
    /// Creates a library-generated failure. Deliberately does not accept an inner exception: retaining the
    /// cause would re-expose the value that failed to bind.
    /// </summary>
    internal EnvarsException(
        string message,
        EnvarFailureKind failureKind,
        string? environmentVariableName,
        Type? optionsType,
        string? optionsName,
        string? propertyName,
        Type? targetType,
        string? cultureName,
        Type? binderType,
        string? causeType) : base(message)
    {
        FailureKind = failureKind;
        EnvironmentVariableName = environmentVariableName;
        OptionsType = optionsType;
        OptionsName = optionsName;
        PropertyName = propertyName;
        TargetType = targetType;
        CultureName = cultureName;
        BinderType = binderType;
        CauseType = causeType;
    }

    /// <summary>
    /// Gets the binding stage that failed, or <see langword="null"/> when this instance was not generated
    /// by the library.
    /// </summary>
    public EnvarFailureKind? FailureKind { get; }

    /// <summary>
    /// Gets the name of the environment variable involved in the failure, or <see langword="null"/> when
    /// no valid name was available.
    /// </summary>
    public string? EnvironmentVariableName { get; }

    /// <summary>
    /// Gets the options type being bound, or <see langword="null"/> when this instance was not generated
    /// by the library.
    /// </summary>
    public Type? OptionsType { get; }

    /// <summary>
    /// Gets the options registration name, which is <see cref="string.Empty"/> for default options, or
    /// <see langword="null"/> when this instance was not generated by the library.
    /// </summary>
    public string? OptionsName { get; }

    /// <summary>
    /// Gets the name of the property involved in the failure, or <see langword="null"/> when the failure
    /// is not attributable to a single property.
    /// </summary>
    public string? PropertyName { get; }

    /// <summary>
    /// Gets the property's declared type, including <see cref="Nullable{T}"/> rather than its underlying
    /// type, or <see langword="null"/> when the failure is not attributable to a single property.
    /// </summary>
    public Type? TargetType { get; }

    /// <summary>
    /// Gets the name of the culture used for conversion, or <see langword="null"/> for failures outside
    /// the conversion stage.
    /// </summary>
    public string? CultureName { get; }

    /// <summary>
    /// Gets the runtime type of the binder used for conversion, or <see langword="null"/> for failures
    /// outside the conversion stage.
    /// </summary>
    public Type? BinderType { get; }

    /// <summary>
    /// Gets the full type name of the underlying cause, or <see langword="null"/> when the failure had no
    /// underlying exception.
    /// </summary>
    /// <remarks>
    /// Only the type name is kept. The cause's message is discarded because it commonly quotes the value
    /// that failed to parse.
    /// </remarks>
    public string? CauseType { get; }

    internal static EnvarsException InvalidPropertyShape(
        string environmentVariableName,
        Type optionsType,
        string optionsName,
        string propertyName,
        Type targetType)
    {
        string message =
            $"Property '{optionsType.FullName}.{propertyName}' mapped to environment variable " +
            $"'{environmentVariableName}' is not a supported bind target.";

        return new EnvarsException(
            message,
            EnvarFailureKind.InvalidProperty,
            environmentVariableName,
            optionsType,
            optionsName,
            propertyName,
            targetType,
            cultureName: null,
            binderType: null,
            causeType: null);
    }

    internal static EnvarsException InvalidAttributeName(
        Type optionsType,
        string optionsName,
        string propertyName,
        Type targetType)
    {
        // The offending name is deliberately absent from both the message and the metadata: it came from
        // source, but reproducing malformed text here would let a corrupted name forge message structure.
        string message = $"Property '{optionsType.FullName}.{propertyName}' has an invalid environment-variable name.";

        return new EnvarsException(
            message,
            EnvarFailureKind.InvalidProperty,
            environmentVariableName: null,
            optionsType,
            optionsName,
            propertyName,
            targetType,
            cultureName: null,
            binderType: null,
            causeType: null);
    }

    internal static EnvarsException TypeDiscoveryFailure(Type optionsType, string optionsName, string causeType)
    {
        string message =
            $"Failed to inspect environment-variable bindings for options type '{optionsType.FullName}' " +
            $"(options name '{FormatOptionsName(optionsName)}').";

        return new EnvarsException(
            message,
            EnvarFailureKind.InvalidProperty,
            environmentVariableName: null,
            optionsType,
            optionsName,
            propertyName: null,
            targetType: null,
            cultureName: null,
            binderType: null,
            causeType);
    }

    internal static EnvarsException PropertyMetadataFailure(
        Type optionsType,
        string optionsName,
        string propertyName,
        Type? targetType,
        string causeType)
    {
        string message =
            $"Failed to inspect environment-variable binding metadata for property " +
            $"'{optionsType.FullName}.{propertyName}' (options name '{FormatOptionsName(optionsName)}').";

        return new EnvarsException(
            message,
            EnvarFailureKind.InvalidProperty,
            environmentVariableName: null,
            optionsType,
            optionsName,
            propertyName,
            targetType,
            cultureName: null,
            binderType: null,
            causeType);
    }

    internal static EnvarsException EnvironmentReadFailure(
        string environmentVariableName,
        Type optionsType,
        string optionsName,
        string propertyName,
        Type targetType,
        string causeType)
    {
        string message =
            $"Failed to read environment variable '{environmentVariableName}' for option " +
            $"'{optionsType.FullName}.{propertyName}' (options name '{FormatOptionsName(optionsName)}').";

        return new EnvarsException(
            message,
            EnvarFailureKind.EnvironmentRead,
            environmentVariableName,
            optionsType,
            optionsName,
            propertyName,
            targetType,
            cultureName: null,
            binderType: null,
            causeType);
    }

    internal static EnvarsException ConversionFailure(
        string environmentVariableName,
        Type optionsType,
        string optionsName,
        string propertyName,
        Type targetType,
        string cultureName,
        Type binderType,
        string causeType)
    {
        string message =
            $"Failed to convert environment variable '{environmentVariableName}' to '{targetType.FullName}' " +
            $"for option '{optionsType.FullName}.{propertyName}' (options name '{FormatOptionsName(optionsName)}').";

        return new EnvarsException(
            message,
            EnvarFailureKind.Conversion,
            environmentVariableName,
            optionsType,
            optionsName,
            propertyName,
            targetType,
            cultureName,
            binderType,
            causeType);
    }

    internal static EnvarsException AssignmentFailure(
        string environmentVariableName,
        Type optionsType,
        string optionsName,
        string propertyName,
        Type targetType,
        string causeType)
    {
        string message =
            $"Failed to assign environment variable '{environmentVariableName}' to option " +
            $"'{optionsType.FullName}.{propertyName}' (options name '{FormatOptionsName(optionsName)}').";

        return new EnvarsException(
            message,
            EnvarFailureKind.Assignment,
            environmentVariableName,
            optionsType,
            optionsName,
            propertyName,
            targetType,
            cultureName: null,
            binderType: null,
            causeType);
    }

    /// <summary>
    /// Reduces a caught exception to its full type name, unwrapping the reflection wrapper that
    /// <see cref="PropertyInfo.SetValue(object, object)"/> puts around a throwing setter. Nothing but the
    /// type name is taken, so the cause's message cannot leak the value.
    /// </summary>
    internal static string DescribeCause(Exception exception)
    {
        var cause = exception is TargetInvocationException { InnerException: { } inner } ? inner : exception;
        return cause.GetType().FullName ?? cause.GetType().Name;
    }

    /// <summary>
    /// Renders an options name for inclusion in a message. The default name is shown as
    /// <c>&lt;default&gt;</c>; any other name is escaped so that a name containing a quote, a backslash or
    /// a control character cannot forge or corrupt the surrounding message.
    /// </summary>
    internal static string FormatOptionsName(string optionsName)
    {
        if (optionsName.Length == 0)
        {
            return "<default>";
        }

        var builder = new StringBuilder(optionsName.Length);

        foreach (char character in optionsName)
        {
            switch (character)
            {
                case '\\':
                    builder.Append("\\\\");
                    break;

                case '\'':
                    builder.Append("\\'");
                    break;

                default:
                    if (char.IsControl(character))
                    {
                        builder.Append("\\u").Append(((int)character).ToString("X4", CultureInfo.InvariantCulture));
                    }
                    else
                    {
                        builder.Append(character);
                    }

                    break;
            }
        }

        return builder.ToString();
    }
}
