name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        dotnet-version: [ '8.0.x', '9.0.x' ]

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET 9 (for .slnx support)
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Setup .NET ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Restore
        run: dotnet restore FriendlyEnvars.slnx

      - name: Build
        run: dotnet build --no-restore --configuration Release --framework net${{ matrix.dotnet-version == '8.0.x' && '8.0' || '9.0' }} FriendlyEnvars.slnx

      - name: Test
        run: dotnet test --no-build --configuration Release --framework net${{ matrix.dotnet-version == '8.0.x' && '8.0' || '9.0' }} --verbosity normal FriendlyEnvars.slnx