name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    name: Build and Test
    env:
      VersionSuffix: beta-${{ github.run_number }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET 9 (for .slnx support)
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore FriendlyEnvars.slnx

      - name: Build
        run: dotnet build --no-restore --configuration Release --framework net8.0 FriendlyEnvars.slnx

      - name: Test
        run: dotnet test --no-build --configuration Release --framework net8.0 --verbosity normal FriendlyEnvars.slnx

      - name: Package
        run: dotnet pack --no-build --configuration Release FriendlyEnvars.slnx