name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    name: Build and Test
    env:
      VersionSuffix: beta-${{ github.run_number }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET 9 (for .slnx support)
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore FriendlyEnvars.slnx

      - name: Build
        run: dotnet build --no-restore --configuration Release --framework net8.0 --maxcpucount:1 FriendlyEnvars.slnx

      - name: Test
        run: dotnet test --no-build --configuration Release --framework net8.0 --verbosity normal --logger trx --results-directory TestResults FriendlyEnvars.slnx

      - name: Publish Test Results
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Test Results
          path: TestResults/*.trx
          reporter: dotnet-trx

      - name: Package
        run: dotnet pack --no-build --configuration Release FriendlyEnvars.slnx

      - name: Upload NuGet Package
        uses: actions/upload-artifact@v4
        with:
          name: nuget-package
          path: src/FriendlyEnvars/bin/Release/*.nupkg

      - name: Publish Package Download Link
        run: |
          echo "## 📦 NuGet Package Generated" >> $GITHUB_STEP_SUMMARY
          echo "The NuGet package has been built and is available for download:" >> $GITHUB_STEP_SUMMARY
          echo "- **Package**: FriendlyEnvars.1.0.0-beta-${{ github.run_number }}.nupkg" >> $GITHUB_STEP_SUMMARY
          echo "- **Download**: Available in the [Artifacts section](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}) of this workflow run" >> $GITHUB_STEP_SUMMARY