name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    name: Build and Test

    strategy:
      matrix:
        dotnet-version: [ '8.0.x', '9.0.x' ]
        include:
          - dotnet-version: '8.0.x'
            framework: 'net8.0'
          - dotnet-version: '9.0.x'
            framework: 'net9.0'

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET 9 (for .slnx support)
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Setup .NET ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Restore
        run: dotnet restore FriendlyEnvars.slnx

      - name: Build ${{ matrix.framework }}
        run: dotnet build --no-restore --configuration Release --framework ${{ matrix.framework }} FriendlyEnvars.slnx

      - name: Test ${{ matrix.framework }}
        run: dotnet test --no-build --configuration Release --framework ${{ matrix.framework }} --verbosity normal FriendlyEnvars.slnx