name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    name: Build and Test
    permissions:
      contents: read
      actions: read
      checks: write
    env:
      VersionSuffix: ${{ github.ref == 'refs/heads/master' && 'beta' || format('beta-{0}', github.run_number) }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET 9 (for .slnx support)
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore --maxcpucount:1 FriendlyEnvars.slnx

      - name: Build
        run: dotnet build --no-restore --configuration Release --framework net8.0 --maxcpucount:1 FriendlyEnvars.slnx

      - name: Test
        run: dotnet test --no-restore --no-build --configuration Release --framework net8.0 --maxcpucount:1 --verbosity normal --logger trx --results-directory TestResults FriendlyEnvars.slnx

      - name: Publish Test Results
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Test Results
          path: TestResults/*.trx
          reporter: dotnet-trx

      - name: Pack NuGet Package
        run: dotnet pack --no-build --configuration Release --maxcpucount:1 FriendlyEnvars.slnx

      - name: Upload NuGet Package
        uses: actions/upload-artifact@v4
        with:
          name: nuget-package
          path: src/FriendlyEnvars/bin/Release/*.nupkg